services:
  inference_server:
    build:
      context: ./services/inference_server
    image: agentic-garden/inference-server
    volumes:
      - ./services/inference_server/models:/app/models
      - ./services/inference_server/src:/app/src
    environment:
      - MODEL_NAME=${MODEL_NAME}
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  calculator_server:
    build:
      context: ./services/calculator_server
    image: agentic-garden/calculator-server
    ports:
      - "8082:8000"
    volumes:
      - ./services/calculator_server/src:/app/src
    # FIX: Corrected the command to point to the module within the 'src' directory.
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  cli_agent:
    build:
      context: ./clients/cli_agent
    image: agentic-garden/cli-agent
    depends_on:
      - inference_server
      - calculator_server
    command: tail -f /dev/null
    volumes:
      - ./clients/cli_agent/src:/app/src

