# docker-compose.yml

services:
  agentic-server:
    build: .
    image: agentic-garden
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./src:/app/src
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - PYTHONPATH=/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  coding-agent:
    # We use the same image we already built for the server
    image: agentic-garden
    # This ensures the agent only starts after the server is healthy
    depends_on:
      - agentic-server
    # Override the default command to run our agent script
    # The 'tty: true' and 'stdin_open: true' keep the container running
    # and allow us to attach an interactive terminal.
    command: tail -f /dev/null
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
    # We don't need a GPU for the agent logic
    deploy: {}